#!/usr/bin/env bash
# Quick Reference - Web Scraper Commands

# 🚀 START HERE
echo "Web Scraper - Quick Commands Reference"
echo "======================================="
echo ""
echo "Install all dependencies:"
echo "  npm run install-all"
echo ""
echo "Start development (frontend + backend):"
echo "  npm run dev"
echo ""
echo "Frontend only: npm run dev:client (http://localhost:3000)"
echo "Backend only:  npm run dev:server (http://localhost:5000)"
echo ""
echo "BUILD FOR PRODUCTION:"
echo "  npm run build"
echo ""
echo "RUN PRODUCTION:"
echo "  npm run start:server"
echo ""
echo "DOCKER:"
echo "  npm run docker:build"
echo "  npm run docker:run"
echo ""
echo "QUICK START SCRIPT:"
echo "  bash start.sh          # Development"
echo "  bash start.sh --build  # Build only"
echo "  bash start.sh --prod   # Production"
echo ""
echo "APK GENERATION:"
echo "  npm run build"
echo "  npx cap add android"
echo "  cd android && ./gradlew assembleDebug"
echo "  # APK: android/app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "📚 Documentation:"
echo "  README.md             - Full technical overview"
echo "  DEPLOYMENT.md         - Deployment guide"
echo "  .github/workflows/apk-build.yml - GitHub APK build workflow"
echo ""
echo "🔗 Access Points:"
echo "  Development Frontend: http://localhost:3000"
echo "  Development Backend:  http://localhost:5000"
echo "  API Health:           http://localhost:5000/api/health"
echo ""
